# -*- coding: utf-8 -*-
"""STC TV Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xaB2pJfavA25zbM_EWauhZDZ50GEj49h
"""

import pandas as pd
import numpy as np

# قراءة الملف
df = pd.read_excel('/content/stc TV Data Set_T2.xlsx')

# نظرة سريعة على البيانات
print(df.head())

# 1. تنظيف البيانات وتجهيز التواريخ
df['date_'] = pd.to_datetime(df['date_'])
df = df.drop(columns=['Unnamed: 0'], errors='ignore')

# 2. استخراج يوم الأسبوع (اسم اليوم) لمعرفة أوقات الذروة
df['Day_of_Week'] = df['date_'].dt.day_name()

# 3. حساب متوسط ساعات المشاهدة لكل يوم في الأسبوع وترتيبها تنازلياً
peak_days = df.groupby('Day_of_Week')['Total_watch_time_in_houres'].mean().sort_values(ascending=False)

print("--- أيام الذروة والأكثر مشاهدة بترتيب تنازلي ---")
print(peak_days)

import statsmodels.api as sm

# 1. تجهيز البيانات وتحديد التاريخ كفهرس (Index) مع تحديد التردد اليومي 'D'
df_ts = df.copy()
df_ts.set_index('date_', inplace=True)
df_ts = df_ts.asfreq('D')

# 2. بناء وتدريب نموذج SARIMAX مع إضافة الموسمية الأسبوعية (كل 7 أيام)
# المعاملات (order و seasonal_order) تم ضبطها لتناسب النمط الأسبوعي
model = sm.tsa.statespace.SARIMAX(
    df_ts['Total_watch_time_in_houres'],
    order=(1, 1, 1),
    seasonal_order=(1, 1, 1, 7),
    enforce_stationarity=False,
    enforce_invertibility=False
)
results = model.fit(disp=False)


# 3. التنبؤ بالشهرين القادمين (60 يوماً مستقبلياً)
forecast_steps = 60
forecast = results.get_forecast(steps=forecast_steps)
forecast_df = forecast.summary_frame()

# 4. استخراج التواريخ المستقبلية وقيم التنبؤ
future_dates = pd.date_range(start=df_ts.index.max() + pd.Timedelta(days=1), periods=forecast_steps)
predicted_values = forecast_df['mean'].values

# 5. وضع النتائج في جدول جديد
future_forecast_df = pd.DataFrame({
    'date_': future_dates,
    'Predicted_Watch_Time': predicted_values
})

print("--- أول 5 أيام من التنبؤ المتذبذب المطور ---")
print(future_forecast_df.head())

import matplotlib.pyplot as plt

plt.clf()
plt.figure(figsize=(14, 7))


plt.plot(df['date_'], df['Total_watch_time_in_houres'], label='Historical Data', color='blue', alpha=0.8)


plt.plot(future_forecast_df['date_'], future_forecast_df['Predicted_Watch_Time'], label='60-Day Realistic Forecast', color='red', linestyle='--', linewidth=2)


plt.title('stc TV Advanced Watch Time Forecast (SARIMAX)', fontsize=14, fontweight='bold')
plt.xlabel('Date', fontsize=12)
plt.ylabel('Total Watch Time (Hours)', fontsize=12)
plt.legend(loc='upper right', fontsize=11)
plt.grid(True, linestyle=':', alpha=0.6)


plt.show()