# -*- coding: utf-8 -*-
"""STC Task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1la5b62i0BqTdsbbh6iGeIxEgnP92TvKI
"""

# 1. استيراد المكتبات الأساسية لمعالجة البيانات
import pandas as pd
import numpy as np

# 2. استيراد أدوات بناء أنظمة التوصية وحساب التشابه
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

# 3. قراءة ملف البيانات من الإكسل

df = pd.read_excel('/content/stc TV Data Set_T3.xlsx')

# 4. عرض أول 5 أسطر للتأكد من أن البيانات قُرئت بشكل صحيح
df.head()

# 1. تحويل الجدول الطولي إلى مصفوفة (أفلام × مستخدمين)
movie_features_df = df.pivot_table(index='program_name', columns='user_id_maped', values='rating').fillna(0)

# 2. تحويل المصفوفة إلى مصفوفة مضغوطة (Sparse Matrix) لتسريع المعالجة
movie_features_df_matrix = csr_matrix(movie_features_df.values)

# 3. عرض شكل المصفوفة الجديدة (عدد الأفلام × عدد المستخدمين)
print(movie_features_df.shape)

model_knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=6)

# تدريب الخوارزمية على مصفوفة البيانات المضغوطة
model_knn.fit(movie_features_df_matrix)

# 1. تحديد الفيلم المستهدف والبحث عن ترتيبه (Index) في الجدول
target_movie = "Moana"
movie_index = movie_features_df.index.get_loc(target_movie)

# 2. استخراج المسافات وأرقام الجيران الأقرب للفيلم من النموذج
distances, indices = model_knn.kneighbors(movie_features_df.iloc[movie_index, :].values.reshape(1, -1), n_neighbors=6)

# 3. طباعة النتائج (أعلى 5 توصيات لفيلم Moana)
print(f"أعلى 5 توصيات للأشخاص الذين شاهدوا فيلم ({target_movie}):\n")
count = 1
for i in range(1, len(distances.flatten())):
    recommended_movie = movie_features_df.index[indices.flatten()[i]]
    print(f"{count}. {recommended_movie}")
    count += 1